#ifndef BLACKMAP3_VERSION_H
#define BLACKMAP3_VERSION_H

#define BLACKMAP_VERSION_MAJOR 3
#define BLACKMAP_VERSION_MINOR 0
#define BLACKMAP_VERSION_PATCH 0
#define BLACKMAP_VERSION_STRING "3.0.0"

#define BLACKMAP_BUILD_DATE __DATE__
#define BLACKMAP_BUILD_TIME __TIME__

// Feature flags
#define BLACKMAP_HAVE_EPOLL 1
#define BLACKMAP_HAVE_RUST_FFI 1
#define BLACKMAP_HAVE_METRICS 1
#define BLACKMAP_HAVE_STEALTH 1

#endif // BLACKMAP3_VERSION_H
